name: Manual Trigger Workflow

on:
  workflow_dispatch:

jobs:
  check_permission:
    runs-on: ubuntu-latest
    steps:
    - name: Check user permission
      id: check_permission
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Check if user is a member of devops team
      run: |
        USERNAME=$(jq -r '.actor' < ${{ toJson(steps.check_permission.outputs) }})
        TEAM_ID=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/orgs/ORGANIZATION_NAME/teams?name=devops | jq -r '.[0].id')
        TEAM_MEMBERSHIP=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/teams/$TEAM_ID/memberships/$USERNAME)

        if [ -z "$TEAM_MEMBERSHIP" ]; then
          echo "User is not a member of devops team"
          exit 1
        else
          echo "User is a member of devops team"
        fi
    - name: Workflow tasks
      if: steps.check_permission.outputs.status == 'success'
      run: |
        echo "Running workflow tasks"
